---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-deployment-role
  namespace: user
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
    verbs:
      - create
      - get
      - list
      - edit
      - patch
      - watch
      - rollout  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-deployment-rolebinding
  namespace: user
roleRef:
  apiGroup: ""
  kind: Role
  name: user-deployment-role
subjects:
  - kind: User
    name: dev
    apiGroup: ""

